name: Day 3 CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Starting build..."
          test -f app.txt
          test -f app-build.txt
          echo "Build successful!"

      - name: Test
        run: |
          echo "Running tests..."
          test -f test.txt
          grep "CI/CD Test Passed" test.txt
          echo "All tests passed!"

      - name: Build Docker image
        run: |
          docker build -t cicd-day3-app .